# pyvips supports cffi ABI and API mode
#
# During setup.py, it will attempt to compile a generated wrapper against the
# libvips headers -- this is why it needs pkgconfig and libvips in host.
#
# At runtime, it will first try to load the compiled wrapper, and if that
# fails, will fall back to ABI mode, ie. directly opening the libvips shared
# library and calling into it with cffi.

# Skip win since libvips is not packaged for conda there. It is blocked on
# at least gdk-pixbuf.

{% set name = "pyvips" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libvips/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 252819173f4d3737c516c5b81aa3c82a92a21f666633705ecf239a0b33e95899

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    # 2021/12/30 hmaarrfk
    # I'm really not sure how to ensure that things get cross compiled correctly
    # Therefore, we rely on ABI mode for cross compiled architectures
    # - cffi                                   # [build_platform != target_platform]
    # - pkgconfig                              # [build_platform != target_platform]
    # - libvips                                # [build_platform != target_platform]
  host:
    - cffi >=1.0
    - libvips
    - glib
    - pip
    - pkgconfig         # [not win]
    - python
  run:
    - cffi >=1.0
    - python

test:
  requires:
    - pip
  imports:
    - pyvips
  commands:
    - pip check

about:
  home: https://github.com/libvips/pyvips
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Binding for libvips
  doc_url: https://libvips.github.io/pyvips/

extra:
  recipe-maintainers:
    - jcupitt
    - hmaarrfk
