# pyvips supports cffi ABI and API mode
#
# During setup.py, it will attempt to compile a generated wrapper against the
# libvips headers -- this is why it needs pkgconfig and libvips in host.
#
# At runtime, it will first try to load the compiled wrapper, and if that
# fails, will fall back to ABI mode, ie. directly opening the libvips shared
# library and calling into it with cffi.

# Skip win since libvips is not packaged for conda there. It is blocked on 
# at least gdk-pixbuf.

{% set name = "pyvips" %}
{% set version = "2.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libvips/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 24f71106de2000153ca3654f5815c620c239bc6e980b72484ae5e121ecbe4f5a

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cffi >=1.0
    - libvips >=8.12
    - pip
    - pkgconfig         # [not win]
    - pytest
    - pytest-runner
    - python
  run:
    - cffi >=1.0
    - python

test:
  imports:
    - pyvips

about:
  home: https://github.com/libvips/pyvips
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Binding for libvips
  doc_url: https://libvips.github.io/pyvips/

extra:
  recipe-maintainers:
    - jcupitt
    - hmaarrfk
