travis:
  secure:
    BINSTAR_TOKEN: fcUQjsZZKzmddzvTo0XM+QkPDgzXkUG0DtXdUjWlf6HYY4qCBuHk0p7AGPK4VsCiXDf8cqMuy2BUy+oS/yIfwu6a47djQ54C8g7TPjJIT97vgmB5dLoEohzHgMVpXNaJl3IaKeXf+rXsHoxT7phfUw5eBeL4tyG25X5GWaYGbbmWP+UvxcRsJt1reRQT6Rm/OeU5zmQY9DucOHABKsKr8R1qyyDfLdGB4HmsGE+aweC4nNgxXy+bUUYKMHawNNbw4fxTyb3vcht0WXUGG8ZWydeMKSeMopyi/qTnPrD/r6k9uWGk8n+R2y0TWtXlKenaSy30lXUwXLIGXEzhDslzonJmidnpOcuT8vZkgupSBOlm2Pza/3kqRI3Y+/QrETTv6kILvM4yHJheYBnOOY7VxTczByqhoHcOUqw3pOL5ABbGuFIC7u8G22Z6bqXSEGkIygKnLPxigP+JfdG/SZcIhAL6c1hcr1Vquo1YylbCXImZG09PWt0tQ464umKz+vwjFUgfbAok8uG6yM8cviExwH7gsq6SeggdNv/r/tc74n5gFUBruPJRU4pJVKoLHCghBMkdWY7YbbkDDgPdAVfZK+5pcwB8APXKX0qTy9RfAGvVI24G8vkU4Z7YJTxmlVTBWRNRqHtJ3gMCLnq/5eiiZUd9wfU7keQ+kU+m+WQ6D2U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
